### ISSUE TITLE
PICKit

### ISSUE THREAD

**Issue by MalumK** [lcgamboa/picsimlab#26]
Hi! Is PIC microcontrollers compatible with PICKit protocol? For example. I need to connect virtual PICKit to virtual PIC and overwrite one section of eeprom and then reboot the controller.

**Comment by lcgamboa** [comment]
Hi, it is not compatible with the PICKit protocol. I also don't know about a virtual PICKit. 
You can use the mplabx integration plugin to write/read and debug (but it does not support partial memory write). 
https://lcgamboa.github.io/picsimlab/MPLABX_Integrated_Debug_pic.html
https://github.com/lcgamboa/picsimlab_md

The plugin uses a PICSimLab protocol that uses a TCP/IP socket connection. 
It is possible to implement a client to connect to PICSimLab and read/write the memories of the microcontrollers.
Look at:
PICSimLab server implementation: https://github.com/lcgamboa/picsimlab/blob/master/src/devices/mplabxd.cc
MPLABX plugin client: https://github.com/lcgamboa/picsimlab_md/blob/master/src/com/picsim/picsimlab/PicsimLab.java

I have a simple client version in c, if you are interested I can share the code.

The FLASH and EEPROM memory of the microcontrollers are saved in a ".hex" intel hex file format when PICSimLab is closed. It is also possible to edit this file to change memory contents before running PICSimLab. (Or use the menus options "save hex" and "load hex" ).

Hope this helps. Otherwise specify in more detail what you want.
