### ISSUE TITLE
28Pin PIC devices Crash on Hex Load

### ISSUE THREAD

**Issue by caroper** [lcgamboa/picsimlab#28]
I have just installed the latest version of PICSimLab and was pleased to see the "BreadBoard" option and its updated Device list.
Unfortunately the first devices that I tested with it, namely the  PIC16f18855 and PIC16f1788, both crashed the simulator upon loading the HEX file.

In Both cases I was using a Simple GCBASIC source that was compiled and verified on real hardware first.
`
#chip 16f18855

Dir PortA Out

Do
  PortA = NOT PortA
  Wait 250 ms
Loop

`

![PICSimLab Crash](https://user-images.githubusercontent.com/5575801/106944963-ea7b3900-672f-11eb-9e54-91ffbfe6af88.png)

The older devices that were included in the previous versions of PICSimLab appear to work in the Breadboard but not the newer 28 Pin Devices.

Regards
Chris

**Comment by lcgamboa** [comment]
The problem was in picsim and it has already been fixed  https://github.com/lcgamboa/picsim/commit/18b3156ab7664e0ced34496c1c79331ba81062bd 
The 28-pin devices have PORTE registers but do not have LATE, PICsim failed to try to update LATE. 

I will update the files for download tomorrow and let you know here. 

Thanks for the collaboration.

**Comment by lcgamboa** [comment]
I updated the files for download, now it should work without problems.

**Comment by caroper** [comment]
Thank you for the quick response.
I look forward to continuing my tests.
