### ISSUE TITLE
Board 2 - LCD

### ISSUE THREAD

**Issue by Anobium** [lcgamboa/picsimlab#5]
Board 2 - LCD locks up when defining custom characters.   
1. Define character in array - works 
2. Send character to LCD - fail. Locks up the Sim.

I can provide code when you review this issue.

**Comment by lcgamboa** [comment]
I would be grateful if you could send me the code. It will be easier to try to locate the problem. I'll be waiting.

**Comment by Anobium** [comment]
File are in Github.

This error is an interaction between the LCD and something else (I do not what is causing the lock-up).

Files provided.  
**Baseline** - code to show the custom character programming approach works.  See https://github.com/Anobium/Great-Cow-BASIC-Library-Development/blob/master/PCF8563%20Clock/PICSIMIssues/16f648a_Serial_LCD_001.gcb

**Error Code** - this is the development program. Compile and test.  Them, uncomment line 142... CreateCustomCharacters.  Lock ups. See https://github.com/Anobium/Great-Cow-BASIC-Library-Development/blob/master/PCF8563%20Clock/PICSIMIssues/i2c_PCF8563_16f648a_Serial_LCD.gcb

**Comment by Anobium** [comment]
Memory location 295 is in the second bank of memory, it is not shared RAM, So, this valid.  Table 4.1 on the device datasheet shows to be a valid memory location.

**Comment by lcgamboa** [comment]
You're correct, I looked at the memory map of PIC16F627/628 instead of PIC16F648. 
That was not the problem. 
Apparently the problem is on the LCD. 
The simulator does not hang, after the call of the CreateCustomCharacters function only the LCD crashes.
Forcing an LCD configuration reset after the function, as in the code below, the program works normally.
```
;----- Program

  CreateCustomCharacters
  INITLCD

  LCDCursor CURSOROFF

```
I could not identify exactly what causes the error yet. I'll keep looking for the problem.

**Comment by Anobium** [comment]
Any progress?

**Comment by lcgamboa** [comment]
Sorry, but I recently moved and I'm without an internet connection. As soon as I get the house in order and have a work break I will check this problem in more detail.

**Comment by lcgamboa** [comment]
I think the problem is in the LCDCURSOR function. When the CURSOROFF value (13) is passed to the function, it sends the command (8) to the LCD, which is the LCD OFF command.

LCDINIT change LCD_STATE to 12, but  the call of CREATECUSTOMCHARACTERS->LCDCREATECHAR->LCDNORMALWRITEBYTE change the LCD_STATE to 8.

In the code section of the LCDCURSOR  function below, the variable LCD_STATE is set to 8, when it performs the AND operation with 13 it turns 8:

```
;IF LCDCRSR = CURSOROFF THEN LCDTEMP = LCD_STATE AND CURSOROFF
	MOVLW	13
	SUBWF	LCDCRSR,W
	BTFSS	STATUS, Z
	GOTO	ENDIF31
	MOVLW	13
	ANDWF	LCD_STATE,W
	MOVWF	LCDTEMP
```
If the CREATECUSTOMCHARACTERS function is not called the LCDCURSOR function works without problems because the variable LCD_STATE will be set to the value 12 by the LCDINIT function before the LCDCURSOR function call.

**Comment by Anobium** [comment]
Yes, but, this code works on a real LCD.

**Comment by lcgamboa** [comment]
I don't have one PIC16F648A to test in hardware. 
But in my opinion the problem is in the code on end of function LCDNormalWriteByte in lcd.h of gcb:
```
      IF LCDByte < 16 then
         if LCDByte > 7 then
            LCD_State = LCDByte
         end if
      END IF
```
The code test the LCDByte parameter of function without verify if is data or command! 
Any data of a customized  character between 8 and 15 is assigned to the variable LCD_State!

the correct code would be:
```
     IF LCD_RS = 0 then
      IF LCDByte < 16 then
         if LCDByte > 7 then
            LCD_State = LCDByte
         end if
      END IF
     END IF 
```
with this modification everything works normally using Great Cow BASIC (0.98.04 2018-10-20 (Linux 64 bit))

**Comment by Anobium** [comment]
Let me speak with the LCD Design Authority - I will get back asap

**Comment by Anobium** [comment]
We should make the change to the Great Cow BASIC library.  Testing LCD_RS looks to be valid.

Closing issue.
