### ISSUE TITLE
Cannot build PICSimlab 0.8.12 from source

### ISSUE THREAD

**Issue by cemonem** [lcgamboa/picsimlab#77]
Hello,

It seems that lcgamboa/qemu_stm32 is not public now, and since building PICSimlab depends on it I cannot build it from source. I use Ubuntu 18.04 myself, and if I am guessing correctly .deb packages are for Ubuntu 20.04 only, and the AppImages will not work below 20.04 (it gives execv error: No such file or directory - even though libfuse2 is installed).

Is there a reliable way for me to install 0.8.12?

**Comment by lcgamboa** [comment]
Hi @cemonem ,
sorry for the inconvenience. Github doesn't allow more than one fork of the same project, I was having trouble syncing qemu-esp32 support together with qemu-stm32 in the qemu_stm32 fork. Due to limitations, I had to delete this fork and create another one based on the root of the project: https://github.com/lcgamboa/qemu
The updated paths are now:
https://github.com/lcgamboa/qemu/tree/picsimlab-stm32
https://github.com/lcgamboa/qemu/tree/picsimlab-esp32

Consider using the updated version of the scripts to compile PICSimLab from source:
https://github.com/lcgamboa/picsimlab/blob/master/bscripts/build_all_and_install.sh
https://github.com/lcgamboa/picsimlab/blob/master/bscripts/build_all_static.sh

Github actions is no longer supported for ubuntu 18.04 and Appimages does not support wxwidgets well on different Linux versions.
