### ISSUE TITLE
Error loading saved Workspace on Windows

### ISSUE THREAD

**Issue by peterm02019** [lcgamboa/picsimlab#78]
Hi,
 Thank you very much for all the work which has obviously gone into this software project. It looks good so far (I'm a new user), but I'm having a couple of issues with it and I hope that we can get these sorted out so I can begin using it with confidence.

I am getting this error (see attached screenshot) when trying to Load a previously saved Workspace in PICSimLab. I think I see the problem, at least on the surface. I think that Windows is bound to fail trying to find a path with forward slashes in it, but perhaps this may not be the whole story? 

![PICSimLab error 230413a](https://user-images.githubusercontent.com/53995433/231670479-54edf17c-5095-4650-8199-6e72e4a456e7.png)

Of course, now that I try it again from scratch, the error does not occur! I'll leave it here anyway in case it provides a clue as to something which might come back to bite later.

Thanks very much & have a great day!

**Comment by lcgamboa** [comment]
Hi @peterm02019 ,

slashes in the file path are not a problem for the wxwidigets used by PICSimLab. 
The workspace file is a zipped file. When PICSimLab opens the pzw file it is unzipped inside the temp folder. I believe that your problem can be caused by some antivirus checking the file and making it unavailable at the time of reading. I can't reproduce the problem on my computer to try to eliminate it.
Do you use any kind of antivirus? Can you reproduce the problem? Any tips and more information are welcome.
Thank you for contacting us.

**Comment by peterm02019** [comment]
Thank you Luis.

I have not been able to get this problem to happen again, and I'm sorry for
not getting back to you. Too much in action here.

Thank you for taking care of it. Sorry for a late reply. For some unknown
reason, some of my emails arriving are confused by my normal program.

All the best,
Peter
