### ISSUE TITLE
The application freeze and exit on gpboard

### ISSUE THREAD

**Issue by eagl1** [lcgamboa/picsimlab#82]
Hi,

I'm just trying other boards, and I wanted to try the gpboard, but when I selected debug, the application got freeze and exited.

![image](https://github.com/lcgamboa/picsimlab/assets/14331173/18daffa4-023c-4bc7-b37b-d6efdb7f648e)

**Comment by lcgamboa** [comment]
Hi @eagl1,

the problem that you detected is not because of the debug, but because this specific microcontroller does not have all the configuration words implemented in the gpsim simulator. It was fixed in commit 847292f .

The gpboard doesn't have debug support implemented yet.  Consider using breadboard board that supports PIC18F4550 and debug.

Thank you for reporting the problem.

**Comment by eagl1** [comment]
Do you mean I can update the simulator ?
